package main

import (
	"archive/zip"
	"fmt"
	"io"
	"strings"
)

func main() {
	// Check if test.docx looks like it was generated by Word or by our converter
	// Word-generated docx typically has different XML structure
	files := []string{"testfie/test.docx", "testfie/test_new7.docx", "testfie/test_new8.docx"}

	for _, f := range files {
		fmt.Printf("\n=== %s ===\n", f)
		doc := readZipEntry(f, "word/document.xml")

		// Check for Word-specific markers
		if strings.Contains(doc, "mc:Ignorable") {
			fmt.Println("  Has mc:Ignorable (Word-generated)")
		}
		if strings.Contains(doc, "w14:") {
			fmt.Println("  Has w14 namespace (Word 2010+)")
		}
		if strings.Contains(doc, "w15:") {
			fmt.Println("  Has w15 namespace (Word 2013+)")
		}

		// Check the XML declaration and root element
		if len(doc) > 500 {
			fmt.Printf("  First 500 chars: %s\n", doc[:500])
		}

		// Check styles.xml for Word markers
		styles := readZipEntry(f, "word/styles.xml")
		if strings.Contains(styles, "mc:Ignorable") {
			fmt.Println("  styles.xml has mc:Ignorable")
		}
		fmt.Printf("  styles.xml size: %d\n", len(styles))

		// Check settings.xml
		settings := readZipEntry(f, "word/settings.xml")
		fmt.Printf("  settings.xml size: %d\n", len(settings))
		if len(settings) > 300 {
			fmt.Printf("  settings first 300: %s\n", settings[:300])
		} else {
			fmt.Printf("  settings: %s\n", settings)
		}
	}
}

func readZipEntry(zipPath, entry string) string {
	r, err := zip.OpenReader(zipPath)
	if err != nil {
		return fmt.Sprintf("ERROR: %v", err)
	}
	defer r.Close()
	for _, f := range r.File {
		if f.Name == entry {
			rc, _ := f.Open()
			data, _ := io.ReadAll(rc)
			rc.Close()
			return string(data)
		}
	}
	return "NOT FOUND"
}
